version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/data:/app/app/data
      - ./app/models:/app/app/models
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: python app/main.py

  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/workspace
    command: /bin/bash
    stdin_open: true
    tty: true 