llm:
  model: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 1000

tone_styles:
  original: "casual and authentic"
  precise: "clear and concise"
  professional: "formal and business-oriented"

output:
  formats:
    - markdown
    - pdf
  directory: "app/data/output"

embeddings:
  service_type: "openai"  # Options: "local" or "openai"
  models:
    local: "all-MiniLM-L6-v2"
    openai: "text-embedding-ada-002"
  cache_dir: "app/models/embeddings"

paths:
  profiles: "app/data/profiles"
  jobs: "app/data/jobs"